# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eac823e6c571d8e299476f07ab37e3cecdc6e7ac423e4a40e8533777cbec0f4084a40b877e5b79e68178c28a23b4ba2bd87fb0da50cafd8a8d53810f6dafe3d

test:
  secret_key_base: 85490465e6c15727c3b7d047c60ee96c5a1263c336d9f0b8b1e9f0eea4fb01fa6da5fdb68f179c6a5dbd3e629d5ca58111c0feb7bb62bb374697397cf2a97c17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
